### ISSUE TITLE
此插件可能会导致Mirai出现崩溃闪退现象

### ISSUE THREAD

**Issue by byx2020** [Hellobaka/WordCloud#1]
此问题是在我更新本插件到1.0.3和1.0.4版本后、更新Mirai到2.7.1-dev-1和2.7.1版本后才开始出现，而且错误日志里面没有显示崩溃闪退现象发生的具体原因(这让我纠结了挺长时间到底是Mirai的问题还是插件的问题)。

问题刚出现时，我从错误日志判断以为是我的java出现了问题，于是尝试了重新安装Java，之后并分别尝试安装了java11、java15，但问题仍然存在，后续我决定在新文件夹通过MCL重新安装了Mirai并迁移数据，不过问题仍然未解决。

后面我意识到可能是安装的某个插件出现了问题，于是通过控制变量法花了两三天时间测试，才基本确定了问题发生的原因应该与本插件存在强相关性。

目前我有3个正在运行的Mirai机器人(版本相同环境相同)，但出现了崩溃闪退现象的只有安装了此插件的那一个机器人，其他没有安装此插件的Mirai机器人从未出现过这个问题。

如果在出现崩溃闪退后立即重启Mirai，很快就又会出现崩溃闪退，反复测试几次都是这样，但若在某一次重启前将me.cqp.luohuaming.WordCloud.dll文件移出plugins文件夹，然后再重启，就不会出现崩溃闪退现象了。

另外，崩溃闪退现象的出现频率并不固定，从几十分钟到十几个小时都有可能(崩溃闪退后立即重启属于特例)，而且错误日志显示的是“Java 运行时环境检测到一个致命错误”，因此我花了几天时间一步一步缩小范围才慢慢从现象反推出了原因，但仍然不能完全确定这一定就是本插件直接导致的，只能说是最可能的原因，希望大佬可以帮忙判断一下。

以下为插件运行环境信息：
服务器配置：2C4G
操作系统：Windows Server 2012 R2 DataCenter 64bitCN
JRE版本：OpenJDK Runtime Environment Temurin-11.0.12+7 (11.0.12+7) (build 11.0.12+7)
Java VM：OpenJDK Client VM Temurin-11.0.12+7 (11.0.12+7, mixed mode, serial gc, windows-x86)
Mirai版本：2.7.1
插件版本：1.0.4

Mirai崩溃闪退后生成的错误日志(由于内容较多，此处仅贴出部分，完整内容见附件)：
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (0xe0434352), pid=5876, tid=11564
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.12+7 (11.0.12+7) (build 11.0.12+7)
# Java VM: OpenJDK Client VM Temurin-11.0.12+7 (11.0.12+7, mixed mode, serial gc, windows-x86)
# Problematic frame:
# C  [KERNELBASE.dll+0x156e8]
#
# Core dump will be written. Default location: C:\Software\Mirai-0\hs_err_pid5876.mdmp
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: mcl.jar

Host: Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz, 2 cores, 3G,  Windows Server 2012 R2 , 64 bit Build 9600 (6.3.9600.19843)
Time: Wed Sep 22 07:42:38 2021 ?D1ú±ê×?ê±?? elapsed time: 27132.966123 seconds (0d 7h 32m 12s)

---------------  T H R E A D  ---------------

Current thread (0x156bac00):  JavaThread "MiraiNative Events-3" daemon [_thread_in_native, id=11564, stack(0x24350000,0x243a0000)]

Stack: [0x24350000,0x243a0000],  sp=0x2439efc0,  free space=315k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
```
[hs_err_pid5876.log](https://github.com/Hellobaka/WordCloud/files/7207441/hs_err_pid5876.log)
[hs_err_pid12108.log](https://github.com/Hellobaka/WordCloud/files/7207442/hs_err_pid12108.log)

**Comment by Hellobaka** [comment]
感谢反馈，我尝试捕获一下错误（mirai的日志实在看不懂
如果可以的话，可以用数据库工具看一下崩溃时发了点什么消息吗，数据库是sqlite，Navicat就可以看

**Comment by byx2020** [comment]
> 感谢反馈，我尝试捕获一下错误（mirai的日志实在看不懂
> 如果可以的话，可以用数据库工具看一下崩溃时发了点什么消息吗，数据库是sqlite，Navicat就可以看

好的，我刚刚安装好Navicat去看了一下，但没发现崩溃时群友发送的消息有什么异常之处(如下图)，就挺奇怪的，我之前也盯了两三天，崩溃似乎是没有规律的(除了在崩溃闪退后立即重启会大概率又崩溃)，感觉应该不是群友发送的消息导致的，另外，大佬你如果还需要什么信息来判断问题原因，可以尽管和我说，我会全力配合提供的。
![image](https://user-images.githubusercontent.com/58938653/134278905-91538781-6ef4-4ddd-8cef-37beb9eff82b.png)
![image](https://user-images.githubusercontent.com/58938653/134283195-5ba68545-d486-41ea-8d4c-220cf92b8538.png)

**Comment by Hellobaka** [comment]
> > 感谢反馈，我尝试捕获一下错误（mirai的日志实在看不懂
> > 如果可以的话，可以用数据库工具看一下崩溃时发了点什么消息吗，数据库是sqlite，Navicat就可以看
> 
> 好的，我刚刚安装好Navicat去看了一下，但没发现崩溃时群友发送的消息有什么异常之处(如下图)，就挺奇怪的，我之前也盯了两三天，崩溃似乎是没有规律的(除了在崩溃闪退后立即重启会大概率又崩溃)，感觉应该不是群友发送的消息导致的，另外，大佬你如果还需要什么信息来判断问题原因，可以尽管和我说，我会全力配合提供的。
> ![image](https://user-images.githubusercontent.com/58938653/134278905-91538781-6ef4-4ddd-8cef-37beb9eff82b.png)
> ![image](https://user-images.githubusercontent.com/58938653/134283195-5ba68545-d486-41ea-8d4c-220cf92b8538.png)

好，我下午做个压力测试看看能不能抓到问题

**Comment by byx2020** [comment]
@Hellobaka 问题刚刚又复现了，这次我决定做一个测试，于是我在发现崩溃闪退后，立即重启了Mirai，结果很快就又崩溃闪退了。
然后我这样反复重启了五次，每次在重启之后两分钟内很快就又崩溃了，直到最后一次，我在重启之前将me.cqp.luohuaming.WordCloud.dll文件和me.cqp.luohuaming.WordCloud.json移出了plugins文件夹，然后再进行重启，就没出现崩溃闪退的现象了。

![image](https://user-images.githubusercontent.com/58938653/134294336-3f41736d-da62-4252-8049-cc1cb7319652.png)

注：以下附件为这五次崩溃的日志文件
[hs_err_pid7456.log](https://github.com/Hellobaka/WordCloud/files/7208256/hs_err_pid7456.log)
[hs_err_pid2936.log](https://github.com/Hellobaka/WordCloud/files/7208251/hs_err_pid2936.log)
[hs_err_pid4636.log](https://github.com/Hellobaka/WordCloud/files/7208252/hs_err_pid4636.log)
[hs_err_pid6100.log](https://github.com/Hellobaka/WordCloud/files/7208253/hs_err_pid6100.log)
[hs_err_pid11956.log](https://github.com/Hellobaka/WordCloud/files/7208254/hs_err_pid11956.log)

**Comment by Hellobaka** [comment]
下午试着进行了1w条的数据压力测试，但依旧没有发生崩溃。
如果可以的话，试着在 `控制面板-Windows(管理)工具-事件查看器-Windows日志-应用程序` 中找一下有没有类似于.Net Runtime 的错误日志

**Comment by byx2020** [comment]
> 下午试着进行了1w条的数据压力测试，但依旧没有发生崩溃。
> 如果可以的话，试着在 `控制面板-Windows(管理)工具-事件查看器-Windows日志-应用程序` 中找一下有没有类似于.Net Runtime 的错误日志

@Hellobaka 没有发现，最近的错误日志似乎都与mirai无关
![image](https://user-images.githubusercontent.com/58938653/134299461-73fe4168-b6d2-4771-af79-5c24e3e0fc19.png)

**Comment by Hellobaka** [comment]
> > 下午试着进行了1w条的数据压力测试，但依旧没有发生崩溃。
> > 如果可以的话，试着在 `控制面板-Windows(管理)工具-事件查看器-Windows日志-应用程序` 中找一下有没有类似于.Net Runtime 的错误日志
> 
> @Hellobaka 没有发现，最近的错误日志似乎都与mirai无关
> ![image](https://user-images.githubusercontent.com/58938653/134299461-73fe4168-b6d2-4771-af79-5c24e3e0fc19.png)

头疼了，我自己还不能复现，试着用cmd或者PowerShell作为外壳来启动mirai吧，这样最后一条消息之后发生了什么最起码能看见。我自己再想办法复现（苦笑

**Comment by byx2020** [comment]
> 头疼了，我自己还不能复现，试着用cmd或者PowerShell作为外壳来启动mirai吧，这样最后一条消息之后发生了什么最起码能看见。我自己再想办法复现（苦笑

@Hellobaka 好的，另外我个人感觉这个问题有可能不是单一因素导致的，因为我之前在较长的一段时间内，都是能够正常使用词云插件的，崩溃闪退的问题是在我将插件更新到1.0.3/1.0.4版本、Mirai更新到2.7.1-dev-1/2.7.1版本后才开始出现，因此问题的产生原因或许是更新插件+更新Mirai两个综合因素导致的，之后等有时间了，我也会去Mirai的论坛问一下

**Comment by byx2020** [comment]
@Hellobaka 大佬方便告知一下你的插件的运行环境(包括java版本、Mirai版本，乃至服务器系统版本等)吗，最近我闲着使用“mcl-installer-1.0.3-windows-amd64.exe”重新部署了一个全新的Mirai(版本2.8.0-M1)，里面只放了一个“mirai-native-2.0.0-beta.1.jar”插件和词云插件(排除其他插件干扰)，然后花了近一周时间挨个使用了Java11-16的所有jre和jdk版本，但最终结果是Mirai均在不到一天时间内就出现了崩溃闪退现象，所以我想要了解一下你的运行环境，尝试配置为和你一样的环境再看看效果。

![V$9NF)1M$F}P2OBNLI}}BEL](https://user-images.githubusercontent.com/58938653/138036970-a8c703be-894a-40ed-93c8-ef721ae308ac.jpg)

以下文件分别为java11、java12、java13、java14、java15、java16的32位jre和jdk环境下的崩溃日志，虽然可能没啥用，但先放到这里，万一之后能用到呢
[hs_err_pid4736 (1).log](https://github.com/Hellobaka/WordCloud/files/7378455/hs_err_pid4736.1.log)
[hs_err_pid816 (1).log](https://github.com/Hellobaka/WordCloud/files/7378457/hs_err_pid816.1.log)
[hs_err_pid3560 (1).log](https://github.com/Hellobaka/WordCloud/files/7378458/hs_err_pid3560.1.log)
[hs_err_pid4000 (1).log](https://github.com/Hellobaka/WordCloud/files/7378459/hs_err_pid4000.1.log)
[hs_err_pid1676 (1).log](https://github.com/Hellobaka/WordCloud/files/7378460/hs_err_pid1676.1.log)
[hs_err_pid2708 (1).log](https://github.com/Hellobaka/WordCloud/files/7378461/hs_err_pid2708.1.log)
[hs_err_pid6400 (1).log](https://github.com/Hellobaka/WordCloud/files/7378462/hs_err_pid6400.1.log)
[hs_err_pid7456 (1).log](https://github.com/Hellobaka/WordCloud/files/7378463/hs_err_pid7456.1.log)
[hs_err_pid8272 (1).log](https://github.com/Hellobaka/WordCloud/files/7378464/hs_err_pid8272.1.log)
[hs_err_pid11956 (1).log](https://github.com/Hellobaka/WordCloud/files/7378465/hs_err_pid11956.1.log)
[hs_err_pid4636 (1).log](https://github.com/Hellobaka/WordCloud/files/7378466/hs_err_pid4636.1.log)
[hs_err_pid6100 (1).log](https://github.com/Hellobaka/WordCloud/files/7378467/hs_err_pid6100.1.log)
[hs_err_pid2936 (1).log](https://github.com/Hellobaka/WordCloud/files/7378468/hs_err_pid2936.1.log)
[hs_err_pid12156 (1).log](https://github.com/Hellobaka/WordCloud/files/7378469/hs_err_pid12156.1.log)
[hs_err_pid5876 (1).log](https://github.com/Hellobaka/WordCloud/files/7378470/hs_err_pid5876.1.log)
[hs_err_pid12108 (1).log](https://github.com/Hellobaka/WordCloud/files/7378471/hs_err_pid12108.1.log)

**Comment by Hellobaka** [comment]
@byx2020 我的主力bot不在mirai上，是[OPQBot](https://github.com/opq-osc/OPQ)，上次测试挂了一天左右没什么事，环境是这样的：
- 系统：Win11 Pro 22478.100
- jre: 
```
openjdk version "1.8.0_302"
IBM Semeru Runtime Open Edition (build 1.8.0_302-b08)
Eclipse OpenJ9 VM (build openj9-0.27.0, JRE 1.8.0 Windows 10 x86-32-Bit 20210730_172 (JIT enabled, AOT enabled)
OpenJ9   - 1851b0074
OMR      - 9db1c870d
JCL      - de702c3174 based on jdk8u302-b08)
```
- Mirai: 2.7.0
- Mirai-Native: mirai-native-2.0.0.jar

Mirai是来自群友封装的整合包，链接放这里了
```
链接: https://pan.baidu.com/s/1ErHav8rev1BCfA5ZbgdBjA 提取码: cp2z
```
不过这个插件也被群里许多用mirai的一起用着，假如每天都会崩溃的话会有人告诉我的

**Comment by byx2020** [comment]
@Hellobaka 好的，感谢大佬抽时间回复，我这就去试一下大佬提供的整合包。

**Comment by byx2020** [comment]
@Hellobaka 我用了大佬提供的整合包，但似乎出现了新的报错……
![image](https://user-images.githubusercontent.com/58938653/138193680-f105c4a4-8c5d-4328-8ab5-81f7be552d96.png)
![image](https://user-images.githubusercontent.com/58938653/138193741-6123367f-d8d3-4427-87a9-e494a9eb601b.png)
![image](https://user-images.githubusercontent.com/58938653/138193756-f2e04d4b-c25e-4cf5-9f5f-e1fa06aaf7a5.png)

**Comment by Hellobaka** [comment]
@byx2020 是有人用匿名的原因……旧SDK可能因为好久没更新失去了对匿名的支持。SDK作者也跑了，短时间内修不了这个……

**Comment by byx2020** [comment]
@Hellobaka 行，那我之后尝试把Mirai和词云插件放在本地电脑上跑一下看看，感觉我的服务器环境可能有问题，虽然不知道问题出自哪里，总之先换几台电脑对照一下看看效果

**Comment by Hellobaka** [comment]
@byx2020 问题应该在于群里有人使用匿名，插件的sdk不能解析这个消息就炸了

**Comment by byx2020** [comment]
> @byx2020 问题应该在于群里有人使用匿名，插件的sdk不能解析这个消息就炸了

@Hellobaka 我刚刚测试了一下，确实是匿名消息导致的，但奇怪的是，有的时候一条匿名消息就炸了，有的时候五六条匿名消息也不会炸，这似乎是一个概率事件……

**Comment by Hellobaka** [comment]
https://www.lanzoui.com/iBymXvod10j?w
滤掉了所有的匿名，实在不想去查为什么随机炸了
![表情包](https://user-images.githubusercontent.com/50934714/138557736-ce449c64-6791-4359-8e35-143626c30651.jpg)

**Comment by byx2020** [comment]
> https://www.lanzoui.com/iBymXvod10j?w 滤掉了所有的匿名，实在不想去查为什么随机炸了 ![表情包](https://user-images.githubusercontent.com/50934714/138557736-ce449c64-6791-4359-8e35-143626c30651.jpg)

@Hellobaka 收到，非常感谢
![表情包](https://user-images.githubusercontent.com/58938653/138559556-7e072f51-1150-4438-8e96-7b48fd72c3ca.jpg)

**Comment by byx2020** [comment]
> https://www.lanzoui.com/iBymXvod10j?w 滤掉了所有的匿名，实在不想去查为什么随机炸了 ![表情包](https://user-images.githubusercontent.com/50934714/138557736-ce449c64-6791-4359-8e35-143626c30651.jpg)

@Hellobaka 用了大佬你给的Mirai整合包和屏蔽匿名消息版插件之后，目前已经可以连续稳定连续运行三天不掉线了，没有再出现崩溃闪退的现象，这个问题应该可以算是用另一种方式解决掉了，是否要关闭这个issues由大佬你这边决定操作吧

**Comment by Hellobaka** [comment]
我觉得问题核心就在匿名上了，你换回自己常用的mirai版本也应该没问题了。我觉得就这样吧，匿名消息也不在统计的范畴之内

**Comment by byx2020** [comment]
> 我觉得问题核心就在匿名上了，你换回自己常用的mirai版本也应该没问题了。

@Hellobaka 我换回之前的mirai版本运行了几天，没有再出现崩溃，看来确实是匿名消息的问题，总算找到原因了。

**Comment by Hellobaka** [comment]
@byx2020 难内
