### ISSUE TITLE
此插件无法在MiraiCQ会出现无法识别qqid的问题

### ISSUE THREAD

**Issue by qmzola** [Hellobaka/WordCloud#2]
如题，下面是MiraiCQ的log

`[DEBUG][Onebot]:OneBotNetImpl
[INFO][OneBot]:OneBot连接成功
[DEBUG][Center]:开始加载插件`me.cqp.luohuaming.WordCloud`
[INFO][Center]:插件`me.cqp.luohuaming.WordCloud`加载成功
[INFO][[水银词云机] 词云生效]:黑名单模式, 共禁用了 0 个群
[INFO][[水银词云机] 载入错误]:输入字符串的格式不正确。
   在 System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   在 System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   在 System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   在 System.Convert.ToInt32(Object value, IFormatProvider provider)
   在 me.cqp.luohuaming.WordCloud.Tool.IniConfig.Linq.IValue.op_Implicit(IValue value) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Tool\IniConfig\Linq\IValue.cs:行号 1416
   在 me.cqp.luohuaming.WordCloud.Tool.IniConfig.Linq.IValue.op_Implicit(IValue value) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Tool\IniConfig\Linq\IValue.cs:行号 1849
   在 PublicInfos.CloudConfig.get_CycleSwitch() 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.PublicInfos\CloudConfig.cs:行号 171
   在 me.cqp.luohuaming.WordCloud.Code.Event_StartUp.CQStartup(Object sender, CQStartupEventArgs e) 位置 E:\酷Q机器人插 件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Code\Event_StartUp.cs:行号 59
[INFO][Center]:插件`水银词云机`启动成功
[INFO][Center]:Center已经开始运行
使用`ls`来查看所有插件
使用`log`来开关log
输入`q`可以安全退出程序
>>>[DEBUG][Center]:收到的消息:
{
   "ClassType" : "GroupMessage",
   "anonymous" : null,
   "font" : 0,
   "group_id" : 543177628,
   "message" : [
      {
         "data" : {
            "text" : "我算一下"
         },
         "type" : "text"
      }
   ],
   "message_id" : 2,
   "message_type" : "group",
   "post_type" : "message",
   "raw_message" : "我算一下",
   "self_id" : 2557354501,
   "sender" : {
      "age" : 0,
      "area" : "unknown",
      "card" : "希萨布丁",
      "level" : "unknown",
      "nickname" : "希萨布丁",
      "role" : "member",
      "sex" : "unknown",
      "title" : "unknown",
      "user_id" : 3042842565
   },
   "sub_type" : "normal",
   "time" : 1640389604,
   "user_id" : 3042842565
}

[DEBUG][Center]:传入GroupEvent的Msg:
我算一下
[INFO][[水银词云机] CQ_setFatal: ]:发现未处理的异常!
System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
参数名: qqId
   在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.Model.QQ..ctor(CQApi api, Int64 qqId) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\Model\QQ.cs:行号 50
   在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.EventArgs.CQGroupMessageEventArgs..ctor(CQApi api, CQLog log, Int32 id, Int32 type, String name, String function, UInt32 priority, Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, String msg, Boolean isRegex) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\EventArgs\CQGroupMessageEventArgs.cs:行号 74
   在 me.cqp.luohuaming.WordCloud.App.Export.CQEventExport.Event_eventGroupMsg(Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, IntPtr msg, Int32 font)

未经处理的异常:  System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
参数名: qqId
   在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.Model.QQ..ctor(CQApi api, Int64 qqId) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\Model\QQ.cs:行号 50
   在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.EventArgs.CQGroupMessageEventArgs..ctor(CQApi api, CQLog log, Int32 id, Int32 type, String name, String function, UInt32 priority, Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, String msg, Boolean isRegex) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\EventArgs\CQGroupMessageEventArgs.cs:行号 74
   在 me.cqp.luohuaming.WordCloud.App.Export.CQEventExport.Event_eventGroupMsg(Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, IntPtr msg, Int32 font)`

**Comment by qmzola** [comment]
> 如题，下面是MiraiCQ的log
> 
    `[DEBUG][Onebot]:OneBotNetImpl [INFO][OneBot]:OneBot连接成功 [DEBUG][Center]:开始加载插件`me.cqp.luohuaming.WordCloud` [INFO][Center]:插件`me.cqp.luohuaming.WordCloud`加载成功 [INFO][[水银词云机] 词云生效]:黑名单模式, 共禁用了 0 个群 [INFO][[水银词云机] 载入错误]:输入字符串的格式不正确。 在 System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) 在 System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) 在 System.String.System.IConvertible.ToInt32(IFormatProvider provider) 在 System.Convert.ToInt32(Object value, IFormatProvider provider) 在 me.cqp.luohuaming.WordCloud.Tool.IniConfig.Linq.IValue.op_Implicit(IValue value) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Tool\IniConfig\Linq\IValue.cs:行号 1416 在 me.cqp.luohuaming.WordCloud.Tool.IniConfig.Linq.IValue.op_Implicit(IValue value) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Tool\IniConfig\Linq\IValue.cs:行号 1849 在 PublicInfos.CloudConfig.get_CycleSwitch() 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.PublicInfos\CloudConfig.cs:行号 171 在 me.cqp.luohuaming.WordCloud.Code.Event_StartUp.CQStartup(Object sender, CQStartupEventArgs e) 位置 E:\酷Q机器人插 件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Code\Event_StartUp.cs:行号 59 [INFO][Center]:插件`水银词云机`启动成功 [INFO][Center]:Center已经开始运行 使用`ls`来查看所有插件 使用`log`来开关log 输入`q`可以安全退出程序
> 
> > > > [DEBUG][Center]:收到的消息:
> > > > {
> > > > "ClassType" : "GroupMessage",
> > > > "anonymous" : null,
> > > > "font" : 0,
> > > > "group_id" : 543177628,
> > > > "message" : [
> > > > {
> > > > "data" : {
> > > > "text" : "我算一下"
> > > > },
> > > > "type" : "text"
> > > > }
> > > > ],
> > > > "message_id" : 2,
> > > > "message_type" : "group",
> > > > "post_type" : "message",
> > > > "raw_message" : "我算一下",
> > > > "self_id" : 2557354501,
> > > > "sender" : {
> > > > "age" : 0,
> > > > "area" : "unknown",
> > > > "card" : "希萨布丁",
> > > > "level" : "unknown",
> > > > "nickname" : "希萨布丁",
> > > > "role" : "member",
> > > > "sex" : "unknown",
> > > > "title" : "unknown",
> > > > "user_id" : 3042842565
> > > > },
> > > > "sub_type" : "normal",
> > > > "time" : 1640389604,
> > > > "user_id" : 3042842565
> > > > }
> 
> [DEBUG][Center]:传入GroupEvent的Msg: 我算一下 [INFO][[水银词云机] CQ_setFatal: ]:发现未处理的异常! System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。 参数名: qqId 在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.Model.QQ..ctor(CQApi api, Int64 qqId) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\Model\QQ.cs:行号 50 在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.EventArgs.CQGroupMessageEventArgs..ctor(CQApi api, CQLog log, Int32 id, Int32 type, String name, String function, UInt32 priority, Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, String msg, Boolean isRegex) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\EventArgs\CQGroupMessageEventArgs.cs:行号 74 在 me.cqp.luohuaming.WordCloud.App.Export.CQEventExport.Event_eventGroupMsg(Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, IntPtr msg, Int32 font)
> 
> 未经处理的异常: System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。 参数名: qqId 在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.Model.QQ..ctor(CQApi api, Int64 qqId) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\Model\QQ.cs:行号 50 在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.EventArgs.CQGroupMessageEventArgs..ctor(CQApi api, CQLog log, Int32 id, Int32 type, String name, String function, UInt32 priority, Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, String msg, Boolean isRegex) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\EventArgs\CQGroupMessageEventArgs.cs:行号 74 在 me.cqp.luohuaming.WordCloud.App.Export.CQEventExport.Event_eventGroupMsg(Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, IntPtr msg, Int32 font)

**Comment by Hellobaka** [comment]
1. 第一个报错是配置`[Cycle]CycleSwitch`的问题，假如没有配置建议在最后加上一句
```ini
[Cycle]
CycleSwitch=0
```
2.  @super1207 似乎是框架的问题，出现这个错误一般是把小于10000的数传给了`QQ`这个参数，但是看json似乎也没什么问题。这个问题每次群消息都会被触发吗，假如这样可以试着用一下`Mirai-Native`

**Comment by qmzola** [comment]
> 



> 1. 第一个报错是配置的问题，假如没有配置建议在最后加上一句`[Cycle]CycleSwitch`
> 
> ```ini
> [Cycle]
> CycleSwitch=0
> ```
> 
> 2. @super1207似乎是框架的问题，出现这个错误一般是把小于10000的数传给了这个参数，但是看json似乎也没什么问题。这个问题每次群消息都会被触发吗，假如这样可以试着用一下`QQ``Mirai-Native`

淦，刚才重新配置了配置文件，又正常了，蛮玄学的

**Comment by qmzola** [comment]
> > 
> 
> > 1. 第一个报错是配置的问题，假如没有配置建议在最后加上一句`[Cycle]CycleSwitch`
> > 
> > ```ini
> > [Cycle]
> > CycleSwitch=0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. @super1207似乎是框架的问题，出现这个错误一般是把小于10000的数传给了这个参数，但是看json似乎也没什么问题。这个问题每次群消息都会被触发吗，假如这样可以试着用一下`` QQ``Mirai-Native ``
> 
> 淦，刚才重新配置了配置文件，又正常了，蛮玄学的

离谱起来了（

**Comment by qmzola** [comment]
> 1. 第一个报错是配置的问题，假如没有配置建议在最后加上一句`[Cycle]CycleSwitch`
> 
> ```ini
> [Cycle]
> CycleSwitch=0
> ```
> 
> 2. @super1207似乎是框架的问题，出现这个错误一般是把小于10000的数传给了这个参数，但是看json似乎也没什么问题。这个问题每次群消息都会被触发吗，假如这样可以试着用一下`QQ``Mirai-Native`

我这用Mirai-Native有亿点点奇怪的问题（
而且这bug，蛮玄学的。出现时间还很随机

**Comment by Hellobaka** [comment]
@qmzola 那我觉得只能等miraiCQ作者来了一起看问题了，摸了（

**Comment by qmzola** [comment]
> @qmzola那我觉得只能等miraiCQ作者来了一起看问题了，摸了（

好的，谢谢

**Comment by qmzola** [comment]
我淦，又出现了（挂不到6分钟

[DEBUG][Center]:收到的消息:
{
   "ClassType" : "GroupMessage",
   "anonymous" : null,
   "font" : 0,
   "group_id" : 543177628,
   "message" : [
      {
         "data" : {
            "text" : "官服白夜第藏"
         },
         "type" : "text"
      }
   ],
   "message_id" : 20,
   "message_type" : "group",
   "post_type" : "message",
   "raw_message" : "官服白夜第藏",
   "self_id" : 2557354501,
   "sender" : {
      "age" : 0,
      "area" : "unknown",
      "card" : "鸢汐",
      "level" : "unknown",
      "nickname" : "鸢汐",
      "role" : "member",
      "sex" : "unknown",
      "title" : "unknown",
      "user_id" : 1696802423
   },
   "sub_type" : "normal",
   "time" : 1640394160,
   "user_id" : 1696802423
}

[DEBUG][Center]:传入GroupEvent的Msg:
官服白夜第藏
[DEBUG][Center]:传入GroupEvent的Msg:
？
[INFO][[水银词云机] CQ_setFatal: ]:发现未处理的异常!
System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
参数名: qqId
   在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.Model.QQ..ctor(CQApi api, Int64 qqId) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\Model\QQ.cs:行号 50
   在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.EventArgs.CQGroupMessageEventArgs..ctor(CQApi api, CQLog log, Int32 id, Int32 type, String name, String function, UInt32 priority, Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, String msg, Boolean isRegex) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\EventArgs\CQGroupMessageEventArgs.cs:行号 74
   在 me.cqp.luohuaming.WordCloud.App.Export.CQEventExport.Event_eventGroupMsg(Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, IntPtr msg, Int32 font)


未经处理的异常:  System.ArgumentOutOfRangeException: 指定的参数已超出有 效值的范围。
参数名: qqId
   在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.Model.QQ..ctor(CQApi api, Int64 qqId) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\Model\QQ.cs:行号 50
   在 me.cqp.luohuaming.WordCloud.Sdk.Cqp.EventArgs.CQGroupMessageEventArgs..ctor(CQApi api, CQLog log, Int32 id, Int32 type, String name, String function, UInt32 priority, Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, String msg, Boolean isRegex) 位置 E:\酷Q机器人插件开发\词云\bot-development-framework\me.cqp.luohuaming.WordCloud.Sdk\Cqp\EventArgs\CQGroupMessageEventArgs.cs:行号 74
   在 me.cqp.luohuaming.WordCloud.App.Export.CQEventExport.Event_eventGroupMsg(Int32 subType, Int32 msgId, Int64 fromGroup, Int64 fromQQ, String fromAnonymous, IntPtr msg, Int32 font``

**Comment by qmzola** [comment]
更新了新版本的MiraiCQ短时间内问题没有复现，故暂时关闭该issue（
